#datasource
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.fame/db/fame
    username: root
    password: root
    schema: classpath:db/h2/schema/*.sql
    # 第三方连接池需要设置为 always
    initialization-mode: always

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true

#log
logging:
  level:
    root: INFO
    com:
      zbw: DEBUG
